options:
  http-port:
    type: string
    default: '3000'
    description: HTTP port
  allow-custom-visualizations:
    type: boolean
    default: true
    description: Allow custom visualizations
  hide-sidenav:
    type: boolean
    default: true
    description: Hide navigation sidebar
