options:
  grpc-port:
    type: int
    default: 8887
    description: The port that the GRPC service will listen to
  http-port:
    type: int
    default: 8888
    description: The port that the HTTP service will listen to
